name: ruzen-server

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: sudo apt install libasound2-dev
    - uses: actions/checkout@v1
    - run: cd server
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
