name: ruzen-server

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: sudo apt install libasound2-dev
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose --manifest-path server/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path server/Cargo.toml
